ALTER TABLE users
ADD COLUMN IF NOT EXISTS bank_account_name VARCHAR(255),
ADD COLUMN IF NOT EXISTS bank_name VARCHAR(255),
ADD COLUMN IF NOT EXISTS bank_account_number VARCHAR(64),
ADD COLUMN IF NOT EXISTS bank_edit_count INTEGER DEFAULT 0;
